scheme = "semver"
strict = true
scopes = ["git-std", "standard-changelog", "standard-commit", "standard-githooks", "standard-version", "release"]

[versioning]
tag_prefix = "v"

[[version_files]]
path = "crates/git-std/Cargo.toml"
regex = '(?m)^version = "([^"]+)"'

[[version_files]]
path = "crates/standard-commit/Cargo.toml"
regex = '(?m)^version = "([^"]+)"'

[[version_files]]
path = "crates/standard-changelog/Cargo.toml"
regex = '(?m)^version = "([^"]+)"'

[[version_files]]
path = "crates/standard-githooks/Cargo.toml"
regex = '(?m)^version = "([^"]+)"'

[[version_files]]
path = "crates/standard-version/Cargo.toml"
regex = '(?m)^version = "([^"]+)"'
