scheme = "semver"
strict = true
scopes = "auto"

[versioning]
tag_prefix = "v"

[[version_files]]
path = "Cargo.toml"
regex = '(?m)^version = "([^"]+)"'

[[version_files]]
path = "Cargo.toml"
regex = 'standard-commit = \{ version = "([^"]+)"'

[[version_files]]
path = "Cargo.toml"
regex = 'standard-changelog = \{ version = "([^"]+)"'

[[version_files]]
path = "Cargo.toml"
regex = 'standard-version = \{ version = "([^"]+)"'

[[version_files]]
path = "Cargo.toml"
regex = 'standard-githooks = \{ version = "([^"]+)"'
